### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by staaph** [Devzstudio/tailwind_to_css#5]
- [ ] fix hotkeys 
- [x] add typescript types
- [ ] add lightmode?
- [ ] 'hover:' property not working (scrape new version of cheatsheet?)
//mobile
- [ ] change mobile textareas to flex column
- [ ] fix github button margin-right for mobile
- [ ] slight overflow (safari, IOS, 4.7 screen)
- [ ] check phone accessibility. screens happen to not react after first convert

**Comment by staaph** [comment]
took hotkeys out. lib not working. Not necessary imo - could write an own hook and add + check user agent and add meta + k symbol on large screens. 
lightmode not necessary. style fits good.
mobile should be alright for now. wont change to flex-col -row looks fine
